### ISSUE TITLE
Compile error in chained operations

### ISSUE THREAD

**Issue by mathstuf** [Dav1dde/gl3n#36]
Fails with GDC 2.064.2. Other compilers untested.

```d
private import gl3n.linalg;

int main(string[] args) {
  vec3 pos = vec3(1, 1, 1);
  vec3 size = vec3(1, 1, 1);
  vec3 of = vec3(1, 1, 1);

  //vec3 fails = pos + size * of;

  vec3 inter = size * of;
  vec3 works = pos + inter;

  return 0;
}
```

```
t.d:9: error: incompatible types for ((pos) + (size.opBinary(of))): 'Vector!(float, 3)' and 'float'
```

**Comment by Extrawurst** [comment]
@mathstuf is your goal to test with all kinds of old compiler versions ? last issue was about 2.065 .. :P

**Comment by mathstuf** [comment]
On Wed, Mar 25, 2015 at 03:16:47 -0700, Stephan Dilly wrote:
> @mathstuf is your goal to test with all kinds of old compiler versions
> ? last issue was about 2.065 .. :P

Well, if GDC were to have a 2.066 release…
