### ISSUE TITLE
v1.0.1 ?

### ISSUE THREAD

**Issue by John-Colvin** [Dav1dde/gl3n#47]
When dmd 2.067 comes out, gl3n v1.0.0 won't compile with it due to not having (some of) the changes from https://github.com/Dav1dde/gl3n/pull/43

A v1.0.1 patch release would be nice.

**Comment by John-Colvin** [comment]
To work with dmd 2.067, this one will also be needed: https://github.com/Dav1dde/gl3n/pull/48

**Comment by Dav1dde** [comment]
I added a tag v1.0.1, I will close this when dub updated the packages.
