### ISSUE TITLE
Matrix decomposition

### ISSUE THREAD

**Issue by SrMordred** [Dav1dde/gl3n#73]
There is no way to do decomposition on gl3n , right?
Like on glm:
`glm::decompose(transformation, scale, rotation, translation, skew, perspective);`

**Comment by Dav1dde** [comment]
There is `mat.get_{translation, scale, rotation}`, they simply return the relevant parts of the Matrix, e.g get_rotation returns the upper left 3x3 Matrix, nothing else.
