### ISSUE TITLE
Compiling example code

### ISSUE THREAD

**Issue by joelcnz** [Dav1dde/gl3n#74]
I don't know what to put for the import thing.

import gl3n.aabb : vec3;

void main() {
	vec4 v4 = vec4(1.0f, vec3(2.0f, 3.0f, 4.0f));
	vec4 v4_2 = vec4(1.0f, vec4(1.0f, 2.0f, 3.0f, 4.0f).xyz); // "dynamic" swizzling with opDispatch
	vec4 v4_3 = v4_2.xxyz; // opDispatch returns a static array which you can pass directly to the ctor of a vector!

	vec3 v3 = my_3dvec.rgb;
	vec3 foo = v4.xyzzzwzyyxw.xyz; // not useful but possible!

	mat4 m4fv = mat4.translation(-0.5f, -0.54f, 0.42f).rotatex(PI).rotatez(PI/2);
	glUniformMatrix4fv(location, 1, GL_TRUE, m4fv.value_ptr); // yes they are row major!

	alias Matrix!(double, 4, 4) mat4d;
	mat4d projection;
	glGetDoublev(GL_PROJECTION_MATRIX, projection.value_ptr);

	mat3 inv_view = view.rotation;
	mat3 inv_view = mat3(view);

	mat4 m4 = mat4(vec4(1.0f, 2.0f, 3.0f, 4.0f), 5.0f, 6.0f, 7.0f, 8.0f, vec4(1,2,3,4), vec4(1,2,3,4)); 
}

**Comment by Dav1dde** [comment]
I don't understand your question. You want to import `vec3`? `import gl3n.linalg : vec3`

**Comment by joelcnz** [comment]
I want to compile an example program. I was expecting a module called 'import gl3n.all' or some thing.

**Comment by Dav1dde** [comment]
Importing everything is a code smell that's why there is no `gl3n.all` module. Furthermore compiling this example doesn't really makes sense, it is just a short overview of what is possible and how you would use it (e.g. `glUniformMatrix4fv` is an OpenGL function which has per se nothing to do with gl3n).
