### ISSUE TITLE
AABBT!int doesn't work

### ISSUE THREAD

**Issue by DrInfiniteExplorer** [Dav1dde/gl3n#77]
It isn't possible to instantiate the `AABBT`-template with an `int`, it gives an error on [this line](https://github.com/Dav1dde/gl3n/blob/master/gl3n/aabb.d#L16) since the constructor of the `vec3`s are hardcoded to be of type `float`.

Proposed solution: instantiate with `cast(type)0.0` instead

Problem observed with `DMD32 D Compiler v2.074.0` on windows

**Comment by Dav1dde** [comment]
You are right, this is wrong. PR welcome, otherwise I am gonna fix this when I have time to setup my development environment again.
