### ISSUE TITLE
Casting between Vector's with different types but the same length does not work

### ISSUE THREAD

**Issue by cosinus2** [Dav1dde/gl3n#85]
```D
vec3 a = cast(vec3)vec3i(1, 2, 3);
```

**Comment by JonathanILevi** [comment]
That can be don with simple constructing it.

`vec3 a = vec3(vec3i(1,2,3));`
Or because of D magic simple
`vec3 a = vec3i(1,2,3);`

`float` to `int` though is not that easy.

**Comment by Dav1dde** [comment]
Sorry been MIA for a bit, thanks for jumping in @JonathanILevi 

@cosinus2 did that answer your question?

Maybe should consider implementing `opCast` for that case...

**Comment by Dav1dde** [comment]
Thanks for answering, I'll assume this has been answered now.

Maybe worth adding an `opCast`, mh...
