### ISSUE TITLE
DUB package is out dated

### ISSUE THREAD

**Issue by RUSshy** [Dav1dde/gl3n#88]
Hi

In dub website, it looks like latest version is from 2016-Jan-07

Is there a particular reason why it wasn't updated ?

Should i stick with that version or should i clone the repo directly ?

Thanks !!

**Comment by Dav1dde** [comment]
I triggered a manual update, so the master version should def. be up to date.

In the meantime there was no new release. I'll see if I can make one this weekend. But nothing much changed, I'd just use the master version.

**Comment by jonathanballs** [comment]
The release package has not been updated since 2016. Is there one planned? I do not really want to rely on ~master since it is liable to change and I would prefer to have control over the version I am depending on.

**Comment by Dav1dde** [comment]
Done.

**Comment by jonathanballs** [comment]
Sorry not sure if the package update was successful - I still only see 1.3.1 in the version list: https://code.dlang.org/packages/gl3n/versions

**Comment by Dav1dde** [comment]
I renamed the package.json to dub.json, I hope that does the trick

**Comment by Dav1dde** [comment]
It's updated now.

**Comment by jonathanballs** [comment]
Thank you - really appreciated.
