### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by Fr3nchK1ss** [Dav1dde/gl3n#90]
The compiler, as of _v2.093.1_, gives a few warnings because of two main deprecations :

1. In **fustrum.d**, lines like 
`@property ref inout(Plane) left() inout { return planes[LEFT]; }`
give a warning, because a ref is returned from a member function, which implies that the compiler must keep track of 'this' (dip25)

2. In **linalg.d**, lines like
`private @property ref inout(vt) get_(char coord)() inout {`
give a warning. The use of _private_ limits the visibility of get_ to the linalg module, but it is then used in several places. See for instance https://github.com/Fr3nchK1ss/Dterrent/runs/1942657117?check_suite_focus=true

I will immediately do a pull request which corrects both deprecations.

**Comment by Dav1dde** [comment]
@Fr3nchK1ss Thanks for the explanations!
