### ISSUE TITLE
[proposal] adding a member function to_axisAngle() in struct Quat

### ISSUE THREAD

**Issue by Fr3nchK1ss** [Dav1dde/gl3n#92]
I have a unittested func which retrieves the axis / angle transformation vector from a Quaternion. This function would be added to the struct Quaternion. This is a common function of linear algebra when it comes to quaternion computations. I use it in a game engine. Prototype:  
`vec3 to_axisAngle()`

What do you think? Is it in the spirit of gl3n? Should I pull request?

**Comment by Dav1dde** [comment]
Sounds good, honestly was surprised that didn't exist. Regarding the naming, I think `to_axis_angle` would fit the rest of the code better.
